name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8

      - name: Run flake8
        run: flake8 src/ tests/ | tee flake8-output.log

      - name: Run black
        run: black --check src/ tests/ | tee black-output.log

      - name: Run tests
        run: pytest | tee pytest-output.log

      - name: Send logs to Loki
        run: |
          LOG_DATA=$(cat flake8-output.log black-output.log pytest-output.log)
          curl -u ${{ secrets.LOKI_USERNAME }}:${{ secrets.LOKI_PASSWORD }} \
            -H "Content-Type: application/json" \
            -X POST ${{ secrets.LOKI_URL }}/loki/api/v1/push \
            -d '{
              "streams": [
                {
                  "stream": {
                    "job": "ci-cd-pipeline"
                  },
                  "values": [
                    ["'"$(date +%s%N)"'", "'"$LOG_DATA"'"]
                  ]
                }
              ]
            }'

