name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8

      # Run linters (flake8)
      - name: Run flake8
        run: flake8 src/ tests/

      # Run code formatter (black)
      - name: Run black
        run: black --check src/ tests/

      # Run tests (if any)
      - name: Run tests
        run: pytest
